### ISSUE TITLE
Unable to find the taskman binary

### ISSUE THREAD

**Issue by jfhovinne** [php-taskman/core#12]
## Steps required to reproduce the problem

$ bin/taskman baz

```
globals:
    options:
        test:
            description: the test option
            default: foo

commands:
    baz:
        description: baz command
        tasks:
            - { task: "run", command: "${options.test}" }

    foo:
        description: foo command
        tasks:
            - echo 'foo'
    bar:
        description: bar command
        tasks:
            - echo 'bar'
```

## Expected Result

Execution of the task.

## Actual Result

[CompletionWrapper]    in task PhpTaskman\CoreTasks\Plugin\Task\RunTask 

  Unable to find the taskman binary 
 [CompletionWrapper]  Exit code 1
